# -*- coding: utf-8 -*-
# EN content — landing taken from the Figma "Landingpage ENG" frame,
# project pages translated from the French case studies.

LANDING_EN = {
    "lang": "en", "other_lang_label": "🇫🇷 FR",
    "title": "Maxime COUDE — Senior Experience Designer Freelance",
    "nav": {"name": "Maxime COUDE", "projects": "Projects", "about": "About", "contact": "Contact me"},
    "hero_h1": "Hi There! I’m Maxime<br>Senior Experience Designer<br>Freelance",
    "hero_sub": "12 years in design<br>Vannes based",
    "about_title": "About me",
    "about_text": "Senior Product Designer with 10+ years of experience, I craft complex journeys across banking, payment and SaaS. I blend product vision, UX/UI excellence and a strong grasp of business stakes to turn ambitious challenges into simple, ergonomic and functional experiences. I work in close collaboration with product, tech and business teams, and now bring generative AI and vibe coding into my practice, on Senior and Lead Product Design engagements.",
    "stats": [("💼", "12 years"), ("📱", "Mobile"), ("🖥️", "Saas")],
    "offers_title": "What can I offer you?",
    "offers": [
        ("Design your new MVP product", "Design and develop your products to make them market leaders."),
        ("Enhance your existing product", "Showcase your product, prioritize it, and transform it to make it indispensable."),
        ("Product consulting", "Analyze, identify, and improve processes within your design team."),
        ("Define your Design strategy", "Prepare your teams, create processes, and ensure the future of your organization."),
        ("Education and training", "Processes and methodologies to guide your teams."),
        ("Make efficient Design Workshops", "Get to know your users, their needs, and involve them."),
    ],
    "see_project": "See the project",
    "feedback_title": "Feedbacks",
    "feedback_text": "Throughout my career, I have had the chance to collaborate with amazing teams. Here are a few numbers and testimonials that sum up these years of experience.",
    "feedback_author_role": "Co-founder @ Sincro",
    "big_stats": [("+20", "Projects delivered"), ("+250", "User interviews & workshops"), ("10 M", "Users reached by my designs")],
    "clients_title": "Other clients",
    "clients": ["Audencia", "SNCF", "Afnor", "Université de Nantes", "Zodiac", "Beteam"],
    "contact_h2": "Want to get in touch?<br>Send me a message",
    "contact_coords": "<strong>Maxime COUDE</strong><br>Product Designer UX/UI Freelance<br>[T] +33(0)6 75 43 44 88<br>[E] maxime.coude@gmail.com",
}

CASE_LABELS_EN = {
    "mission": "The mission", "role": "My role", "tasks": "Main tasks",
    "tasks2": "Secondary tasks", "toolkit": "Design & Research Toolkit",
    "planning": "Planning", "research": "Research deck", "solution": "The solution",
    "impacts": "The impact", "thanks": "Acknowledgements",
    "dpis": ["Discover", "Problem", "Ideation", "Solution"],
    "back": "← Back to projects", "next": "Next project →",
    "proto_note": "Find the prototype on Figma. For confidentiality reasons the prototype is not accessible at the moment.",
}

PROJECTS_EN = [
# ============================================================ MMA
{
 "slug": "mma", "name": "MMA", "brand": "MMA", "brand_logo": "logo-mma.png",
 "accent": "#1D7AD9", "hero_bg": "#FFFFFF", "hero_fg": "#2B097C", "hero_title_color": "#2B097C", "hero_align": "left",
 "hero_title": "Making insurance easier to make life easier",
 "hero_desc": "Reimbursements, claims, relationships with agents. Discover the entire design process that made life even simpler for MMA policyholders.",
 "hero_img": ("mma-hero.png", "MMA mobile app mockups"),
 "mission": ["As a Senior Product Designer, I led the creation of the very first mobile app for MMA, a major insurance player in France, and faced an exciting and complex challenge. Our goal was to create a product with an exceptional user experience from scratch, working closely with the internal product, marketing and development teams. One of the main priorities was to design an app that would meet the diverse needs of MMA users and customers across a wide range of areas, including health, home, car, legal protection, hunting, school insurance, life accidents and multi-risk coverage. To achieve this, we had to tackle several key challenges:"],
 "challenges": [
   ("Needs understanding & research", "Research and create features tailored to users' specific needs in each insurance area."),
   ("Intuitive, cross-product navigation", "Navigate simply across such a wide range of insurance services. Organize information logically and as simply as possible."),
   ("Experience personalization", "Integrate personalization and configuration features based on user preferences. E.g. authentication, notifications, etc."),
   ("Security and confidentiality", "An absolute priority: implement robust security measures to ensure users' sensitive information was optimally protected."),
   ("Accessibility", "Create an interface accessible to people with disabilities and easy to use for everyone, whatever their level of tech proficiency."),
   ("Testing", "Run frequent user tests throughout the development process to gather valuable feedback and adjust accordingly."),
 ],
 "role": ["I led the product design of the mobile app. During this project I had the opportunity to work with the internal teams: Christophe Houze, Head of Digital UX Organization, Virginie Mahé, Digital Project Manager, Rémi Joyaux, Product Manager, Maxime Gourloo, Proximity Product Owner, Lucie Chevrier, UX Designer, and Dorian Macerot, Organization Assistant. I carried out this mission in collaboration with Chris Le Guen, Project Manager at the Team Inside agency, with the support of Riham Dir Akilian, Product Designer at Monsieur Guiz."],
 "tasks": ["Interview and Scope", "Research and ideation", "Design execution and validation", "Design system creation, integration and handover"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Interview", "Card sorting", "Survey", "ZeroHeight"],
 "phases": ["MVP Scope", "Business Research", "User Interviews", "User flow", "Wireframing", "User Interface Design", "Prototyping & Testing"],
 "planning_text": "The project unfolded in 5 main phases: scope definition for the MVP, business research & user interviews, userflow & wireframing, final interface and design system creation, prototyping and user testing.", "planning_img": ("mma-planning.png", "MMA project planning"),
 "research": [
   ("Competition", ["Together with the MMA team, we benchmarked major competitors among other insurance apps with a similar product. We looked at how they present information and organize their home screen.",
                    "Among them: established brands such as GMF, Groupama and Pacifica, but also specialized pure players such as Alan and Luko."], ("mma-concurrence.png", "Competitive benchmark")),
   ("Interviews", ["To better understand our users' expectations, we ran focus groups and individual interviews. This was a fundamental step in the design process of the insurance mobile app. It allowed us to discover what really matters to our users, to solve potential problems before launch and to craft an exceptional user experience. For confidentiality reasons the interviews cannot be shared, but here are the main insights that emerged during this phase."], None),
 ],
 "insights": [
   ("Personalized dashboard", "Offer a personalized, evolving dashboard: latest reimbursements, claim tracking, access to assistance, seasonal news pushes."),
   ("Quick actions", "Quick access to recurring actions depending on contract types: request a reimbursement, report a claim, contact my agent, issue a certificate."),
 ],
 "solution": [
   ("User flow", ["After in-depth reflection and several card-sorting workshops, we started mapping the user journeys. Our goal was to refine the navigation and structure the information architecture so as to maintain a consistent pattern, ensuring easy understanding for all our users."], ("mma-userflow.png", "MMA app user flow")),
   ("Wireframe", ["During the wireframing phase, we materialized the navigation and information architecture concepts, which provided a solid foundation for designing the final interfaces. In parallel, we also worked on various features addressing our users' expectations and pain points. By bringing all these elements together, we carefully designed the patterns and layout of key interactions such as buttons, navigation menus and content areas.",
                  "The collaborative approach played a central role in the success of this phase. It gave us the opportunity to gather valuable ideas and feedback from all stakeholders, which greatly enriched our understanding of user needs."], ("mma-wireframe.png", "MMA app wireframes")),
   ("User interface", ["Once our concepts were validated, I worked on the final UI of the interfaces. Creating a design system was essential to the success of such a project. It enabled us to craft a carefully thought-out user interface, perfectly adapted to every device."], ("mma-ui.png", "MMA app final interfaces")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "As the app is still in development, I am not able to share more information about the impact of our work. The data will be updated soon.",
 "impacts": [("4.7", "Store rating"), ("x %", "Downloads"), ("+100k", "Active users"), ("81 %", "User satisfaction"), ("85-15", "Mobile vs Web usage")],
 "thanks": [
   ("Thanks to the whole MMA team", ["Christophe Houze", "Virginie Mahé", "Rémi Joyaux", "Maxime Gourloo", "Lucie Chevrier", "Dorian Macerot"]),
   ("Thanks also to the external partners", ["Chris Le Guen", "Riham Dir Akilian"]),
 ],
},
# ============================================================ SINCRO SAAS
{
 "slug": "sincro-saas", "name": "Sincro Saas", "brand": "Sincro", "brand_logo": "logo-sincro-white.png",
 "accent": "#4975E9", "hero_bg": "linear-gradient(135deg, #4975E9 0%, #7B61FF 100%)", "hero_fg": "#FFFFFF", "hero_split": True,
 "card_bg": True, "card_text": "left",
 "hero_bg_img": "decor-sincro-gradient.png",
 "hero_title": "The app suite for easier management than ever",
 "hero_desc": "Purchasing, invoicing, vendors, duty of care, time tracking… Discover the design process that simplified the way the intellectual-services ecosystem is managed.",
 "hero_img": ("sincro-saas-hero.png", "Sincro suite interface on desktop"),
 "mission": ["Sincro connects the players of the intellectual-services industry within its SaaS management and intermediation platform, providing them with the tools and services to collaborate in a secure, interconnected environment.",
             "In the ultra-competitive ERP market, Sincro set itself the goal of being the all-in-one SaaS platform enabling all its users to boost and simplify their daily activity. In this context, the main challenge was to redesign and build a product suite serving the different business lines."],
 "challenges": [
   ("Unify the solutions through a single experience", ""),
   ("Create the image & branding", ""),
   ("Build a scalable design system", ""),
   ("Rethink and create the business features", ""),
 ],
 "role": ["As the very first employee hired as a UX/UI Designer at Sincro, I had the privilege of carrying out several major missions for the startup's growth. My journey began with user research, continued with product design, and involved a significant evolution of the user experience by introducing key features, ultimately leading to a complete redesign of the user interface (UI). During this enriching experience, I also played an essential role in creating the visual identity of the Sincro brand, of which we are extremely proud today. I also worked closely with the technical, marketing and sales teams, raising their awareness of user-experience matters while supporting them with my design skills. In conclusion, this experience gave me the opportunity to work within an exceptional team, notably alongside the multi-hat co-founder acting as CTO, Product Manager and Sales, Damien Mordaque, as well as founder Lionel Frizon, and all the development and business teams, around twenty people in total."],
 "tasks": ["Strategic design: Business x Product", "UX Researcher: Interviews, Personas, Experience Maps, Card sorting…", "Brand Designer: Branding", "UX Designer: Userflows, Wireframing, A/B testing", "UI Designer: Final interface design, Design System"],
 "tasks2": ["Motion Designer: Animations", "Graphic Designer: Communication and slide decks", "Design evangelist: Workshop facilitation & knowledge sharing"],
 "toolkit": ["Miro", "Board", "Interview", "Survey", "Card sorting", "Maze", "Sketch", "Zeplin", "Figma", "After Effects"],
 "phases": ["Stakeholders Interview", "Scope Definition", "Business Research", "User Interviews", "Wireframing", "User Interface Design", "Usability Testing", "Design Update"],
 "planning_text": "We mostly worked in an agile format, in 3-week sprints. Below is an example of how one of our Design sprints unfolded.",
 "planning_img": ("sincro-saas-planning.png", "Sincro Design sprint planning"),
 "research": [
   ("Experience Map", ["For every partial redesign of the product and every new feature, we organized several workshops to deepen our understanding of users' expectations and behaviors. Whether by creating experience maps, running individual interviews, organizing card-sorting sessions or using the \"6 to 1\" method, these approaches and methodologies gave us a better understanding of our users and their expectations within their line of business.",
                       "Here is an example of an experience-map creation workshop we ran with a panel of 10 users ahead of the redesign of the Sourcing product."], ("sincro-saas-expmap.png", "Experience Map workshop")),
   ("Site Map", ["I also materialized the site map of the entire solution to share it with the whole product team. For every new feature, this allowed us to define a hierarchical representation of pages and features in order to optimize the user experience. This exercise guarantees a logical organization, better accessibility and a quick understanding of the structure, which ultimately helps increase user satisfaction and experience and fosters retention on the platform."], ("sincro-saas-sitemap.png", "Sincro suite site map")),
 ],
 "insights": [],
 "solution": [
   ("Dashboard", ["The customizable dashboard provides every user with a global view of their activity through interactive widgets. The widgets surface the essential information users need to do their job day to day. Combined with a notification center and a search engine, it guides and facilitates user actions and makes the experience even smoother."], ("sincro-saas-dashboard.png", "Sincro dashboard")),
   ("Contracts list", ["In the management module you will find a list of sales contracts. This list is highly customizable, allowing users to get an overview, manipulate it and carry out individual or bulk actions as needed."], ("sincro-saas-synthese-absences.png", "Contracts list — contract summary, absences")),
   ("Marketplace", ["Boosting the business means fostering growth thanks to the solution's ability to connect talents with each client's entire network. The Sincro Marketplace is a hub centralizing needs that every member company has the opportunity to answer by proposing highly qualified resources."], ("sincro-saas-marketplace.png", "Sincro Marketplace")),
   ("Design system", ["I led, transversally, the design and continuous update of the Sincro Design System. This documentation source allowed all our product and technical teams to dramatically improve our delivery velocity."], ("sincro-saas-designsystem.png", "Sincro Design System components")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "",
 "impacts": [],
 "thanks": [("Thanks to the Sincro team", ["Damien Mordaque", "Kevin Mouzet", "Emile Leenhardt"])],
},
# ============================================================ SINCRO MOBILE
{
 "slug": "sincro-mobile", "name": "Sincro Mobile", "brand": "Sincro", "brand_logo": "logo-sincro.png",
 "accent": "#1FA26A", "hero_bg": "#FFFFFF", "hero_fg": "#000000", "hero_title_color": "#6482D4", "hero_align": "right",
 "card_bg": True, "card_text": "right", "card_fg": "#FFFFFF", "card_title_color": "#FFFFFF",
 "card_bg_color": "linear-gradient(135deg, #4975E9 0%, #7B61FF 100%)", "card_brand_logo": "logo-sincro-white.png", "card_brand_logo_alt": "logo-sincro.png",
 "hero_title": "The pocket app for consultants on assignment",
 "hero_desc": "Time tracking, activity reports, absences. The best everyday app for all consultants.",
 "hero_img": ("sincro-mobile-hero.png", "Sincro mobile app screens"),
 "mission": ["Sincro is the mobile app every consultant on assignment has been waiting for. The service lets users enter their activity time quickly and easily, wherever they are. Thanks to its direct connection with the web solution, users can fill in and complete their monthly activity report on the go. It was also essential to simplify the contract-addition request process, making it more accessible than ever, directly with their manager. For managers, Sincro is a powerful tool that lets them not only add new contracts but also validate reports and get a complete overview, including production time, time spent between contracts and absences across their whole team. The solution also measures the TACE (activity rate excluding leave). Our main goal was to simplify the user experience as much as possible and improve communication between these two user groups. Sincro was designed to be as intuitive and efficient as possible, making time and contract management as simple as possible for every user."],
 "challenges": [
   ("Simplify the time-entry experience", ""),
   ("Replace email requests to managers", ""),
   ("Offer a dedicated communication channel", ""),
   ("Automate & notify entry reminders", ""),
 ],
 "role": ["As Product Designer, I led all the work related to the design of the app. During this project, I had the pleasure of working closely with our internal Product Manager, Damien Mordaque, as well as with the teams of the Creatiwity agency for the app development: Johan Dufau as Lead Mobile Backend Developer and Julien Blatecky as Lead Mobile Frontend Developer."],
 "tasks": ["Interview and Scope", "Research and ideation", "Design execution and prototyping", "Design validation"],
 "tasks2": [],
 "toolkit": ["Miro", "Sketch", "Zeplin", "Interview", "After Effects", "Maze"],
 "phases": ["Scope Definition", "User Interviews", "User flow", "Wireframing", "User Interface Design", "Prototyping", "User testing"],
 "planning_text": "The project unfolded in 4 main phases: scope definition, user interviews, journeys & userflow, wireframing, interface finalization, prototyping and user testing.", "planning_img": ("sincro-mobile-planning.png", "Sincro Mobile project planning"),
 "research": [
   ("Usage analysis", ["First, to build our research deck, we leveraged the web solution's data (KPIs) to analyze how users actually use the platform. Our analysis covered different criteria depending on user typologies: population/audience, mobility, timing of needs, frequency, engagement, performance and satisfaction. We also cross-referenced all this data with individual interviews.",
                       "For confidentiality reasons, the data in the visual above is masked."], ("sincro-mobile-kpi.png", "Web solution KPI analysis")),
   ("Competition", ["In our research deck we also analyzed all the players in the competitive market. This allowed us to identify best practices, but also to audit existing solutions in order to offer an even more intuitive experience when designing the Sincro app."], ("sincro-mobile-concurrence.png", "Competitive analysis")),
 ],
 "insights": [],
 "solution": [
   ("User interface", ["Once the ideation work was explored, we worked on designing the final UIs. Here is a summary."], ("sincro-mobile-ui.png", "Final interfaces overview")),
   ("Documentation", ["To maximize user adoption, we also documented all the features available in the app. This work allowed our clients to promote the app launch internally and increase their employees' engagement."], ("sincro-mobile-doc.png", "Feature documentation")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "After the store release in March 2019, we analyzed app usage versus web usage over the following 3 months. Here are some key figures:",
 "impacts": [("+1500", "Activity reports entered by consultants"), ("+350", "Contracts added by managers"), ("45%", "Users who used the in-app messaging"), ("-36%", "Late submissions of monthly activity reports")],
 "thanks": [
   ("Thanks to the Sincro team", ["Damien Mordaque", "Kevin Mouzet", "Emile Leenhardt"]),
   ("Thanks also to the Creatiwity agency", ["Johan Dufau", "Julien Blatecky"]),
 ],
},
# ============================================================ AFNOR
{
 "slug": "afnor", "name": "Afnor", "brand": "Afnor — Opéra 2", "brand_logo": "logo-afnor.png",
 "accent": "#8C6A45", "hero_bg": "#F3E7DC", "hero_fg": "#2B097C", "hero_title_color": "#2B097C", "hero_align": "left", "card_cta_color": "#2B097C",
 "hero_title": "A single platform, transparent audits",
 "hero_desc": "With more than 3,500 audits, Opéra 2 lets clients follow every step of their audits while simplifying exchanges with auditors within the platform.",
 "hero_img": ("afnor-hero.png", "Opéra 2 platform interface"),
 "mission": ["Launched by Afnor in 2016, OPERA is a SaaS audit-tracking platform. Designed for clients wishing to be audited, it streamlines the process from preparation to decision-making, while allowing clients to collaborate with their auditor and account manager on a shared platform. Initially focused on a graphic redesign and therefore UI design, I supported my clients through a much deeper UX overhaul of the platform."],
 "challenges": [
   ("UX audit & complete ergonomic redesign", ""),
   ("Simplify tracking processes and data entry", ""),
   ("Create a design system", ""),
   ("Reconnect with users", ""),
 ],
 "role": ["As Product Designer, I supported Afnor through the complete ergonomic redesign of the solution, including a user-experience improvement phase all the way to the design of a comprehensive design system. For this project I had the opportunity to work with Afnor's internal team in charge of the Opéra project: Marie Sperandio, Head of Digital Transformation, Ilija Spaargaren, Project Manager, Frédéric Dorinet, Product Owner, and Williams Bouton, CSM. On the development side, the Anakeen agency was represented by Moez Marrakchi, Development Engineer, Lydie Derrien, Projects Director, and Santiago Mauro, Fullstack Developer."],
 "tasks": ["Interview and Scope", "Research and ideation", "Design execution and validation", "Design system creation, integration and handover"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Eye Tracking"],
 "phases": ["Audit", "Shadowing & Eye Tracking", "Information architecture", "Wireframing", "User Interface Design & Prototyping"],
 "planning_text": "The project unfolded in 4 main phases: audit, shadowing & eye tracking, information architecture & wireframing, interface finalization & prototype.", "planning_img": ("afnor-planning.png", "Afnor project planning"),
 "research": [
   ("Shadowing", ["Shadowing is one of the observation methods I set up at the start of the research phase. It allowed me to observe the behavior and interactions of a panel of users with the existing product.",
                  "During the workshop we individually involved 10 users and asked them to carry out their usual tasks on the Opéra 2 platform. We positioned ourselves behind them, taking care not to disturb their environment, in order to observe them using the service. Duration: 40-50 minutes. Finally, we wrapped up the workshop with an ergonomic evaluation grid."], ("afnor-shadowing.png", "Shadowing workshop")),
   ("Eye Tracking", ["Eye tracking is a technology that measures eye movements. This technique lets us understand in detail users' visual journey across an interface, in order to better understand what catches their attention the most. Eye tracking is currently considered a highly accurate UX research method. Setup: Tobii Pro Nano solution.",
                     "During the workshop we individually involved 8 users and asked them to carry out their usual tasks on the Opéra 2 platform. The camera tracked, recorded and analyzed users' eye movements while they used the service."], ("afnor-eyetracking.png", "Eye-tracking workshop — evaluation")),
 ],
 "insights": [],
 "solution": [
   ("The redesign", ["The ergonomic redesign brought harmonization and standardization of the following behaviors: the creation of systems and patterns depending on the page typology — forms, tables, dashboards, etc.; improved input assistance; simplification of tasks thanks to to-do goals (notifications); a navigation overhaul to make it more readable, clear and fluid, combining the sidebar and the tab bar; improved overall readability with tooltips where needed; reduced interface complexity to lighten users' mental load; improved overall performance, notably by reducing response times; and clearer, more understandable wording for the user."], None),
   ("User interface — Dashboard", ["The new dashboard lets users see at a glance the reports awaiting their action, the reports awaiting an auditor action, and the archived reports."], ("afnor-dashboard.png", "Opéra 2 dashboard")),
   ("Audit list & progress", ["The navigation combining a sidebar and a tab bar makes it possible to follow each step of the audit: preparatory review and audit plan, findings, report, comments, final report and exchange area."], ("afnor-audits.png", "Audit list and progress tracking")),
   ("Finding detail", ["Each finding (minor NC, out of scope, etc.) has a detailed sheet gathering the sites involved, the answers and the proposed actions."], ("afnor-constat.png", "Finding detail")),
   ("Final report", ["The validation workflow makes it possible to request corrections or validate the audit report, submit it to the RA and send the final report."], ("afnor-rapport.png", "Final report workflow")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "The ergonomic redesign achieved:",
 "impacts": [("+64 %", "User satisfaction"), ("÷3", "Time needed to complete an audit"), ("+49%", "In-app audit entries"), ("÷2", "Data-entry time"), ("x3", "Development time saved")],
 "thanks": [
   ("Thanks to the whole Afnor team", ["Marie Sperandio", "Ilija Spaargaren", "Frédéric Dorinet", "Williams Bouton"]),
   ("Thanks also to the Anakeen teams", ["Moez Marrakchi", "Santiago Mauro", "Lydie Derrien"]),
 ],
},
# ============================================================ RATP
{
 "slug": "ratp", "name": "RATP", "brand": "RATP — Visiter Paris", "brand_logo": "logo-ratp.png",
 "accent": "#00936E", "hero_bg": "#FFFFFF", "hero_fg": "#2B097C", "hero_title_color": "#00C4B4", "card_cta_color": "#00C4B4",
 "card_bg": True, "card_text": "center",
 "hero_title": "Stay informed to travel with greater peace of mind",
 "hero_desc": "More than 10 million people in France use RATP transport (bus, metro, RER, tramway) every day.",
 "hero_img": ("ratp-hero.png", "Visiter Paris app — alert components"),
 "mission": ["As a user experience designer, I contributed to the creation of the \"Visiter Paris\" app, dedicated to travelers wishing to explore Paris and its surroundings. Given the roughly 10 million travelers who use the RATP urban network daily, it is essential to take into account the sometimes significant transport disruptions, a source of concern for travelers. Our main objective was to design a soothing user experience through the app, to instill a feeling of serenity during their journeys. To achieve this, we implemented solutions to anticipate disruptions, provide real-time information and make travel as pleasant and smooth as possible."],
 "challenges": [
   ("Inform travelers", ""),
   ("Improve peace of mind", ""),
 ],
 "role": ["I was commissioned by RATP to design graphic alert components, while respecting the pre-established guidelines and the existing visual identity. My goal was to ensure these components integrated harmoniously into the defined context, optimizing the experience for end users."],
 "tasks": ["Design execution and validation"],
 "tasks2": [],
 "toolkit": ["Photoshop", "Illustrator"],
 "phases": ["Component creation", "Integration support"],
 "planning_text": "Component creation, then integration coordination.", "planning_img": ("ratp-planning.png", "RATP project planning"),
 "research": [],
 "insights": [],
 "solution": [
   ("User interface — My messages", ["Examples of alert messages designed for the app: \"From July 25 to August 23 inclusive, traffic is interrupted on RER A between La Défense and Auber. Please note: if you wish to visit the Arc de Triomphe (Charles de Gaulle - Étoile station), please use metro lines 1, 2 or 6.\" — \"From July 15 to August 22 inclusive, traffic is interrupted on RER C between Javel, Avenue Henri Martin and Gare d'Austerlitz. Please note: if you wish to visit the Eiffel Tower, the Hôtel des Invalides, the Army Museum or Notre-Dame cathedral, please use the corresponding metro lines.\""], ("ratp-messages.png", "\"My messages\" screens in the Visiter Paris app")),
 ],
 "impacts_text": "Since the integration of alert messages, customer satisfaction has improved by 17%, and 57% of users said they travel with greater peace of mind thanks to real-time information and alerts during their journeys.",
 "impacts": [("+17 %", "User satisfaction"), ("+57 %", "More at ease while traveling")],
 "thanks": [("Acknowledgements", ["Farid Sayah"])],
},
# ============================================================ HELLO PROMO
{
 "slug": "hello-promo", "name": "Hello Promo", "brand": "Hello Promo — Médiaperformances", "brand_logo": "logo-hello-promo.png",
 "accent": "#3FBF61", "hero_bg": "linear-gradient(23deg, #6AE5B3 12%, #66E2B0 30%, #5CD9A8 46%, #54D3A2 54%)", "hero_fg": "#4C4C4C", "hero_align": "left",
 "card_bg": True, "card_text": "left",
 "hero_title": "Get your QR Code and start saving at checkout",
 "hero_title_html": "<span style=\"color:#FFFFFF\">Get your QR Code</span> <span style=\"color:#0A0A0A\">and start saving at checkout</span>",
 "hero_desc": "The app to enjoy instant, paperless discount vouchers at checkout, valid in your hypermarkets.",
 "hero_img": ("hello-promo-hero.png", "Hello Promo web app — QR Code journey"),
 "mission": ["Hello Promo is a marketing solution (Web App) allowing a community of users to benefit from numerous free discounts usable in supermarkets and hypermarkets by presenting a QR Code. Each promotion is accessible through various social channels such as Facebook, Instagram or Twitter. As a senior product designer, I supported my clients in redesigning the \"shopper\" journey to deliver a simpler, more intuitive experience that fosters user sign-up and retention, while respecting personal-data rights."],
 "challenges": [
   ("Simplify sign-up", ""),
   ("Increase retention", ""),
 ],
 "role": ["I led the product design of the web app. During this project I had the opportunity to work with the Médiaperformances team driving the project: Janis Hayat as Head of Marketing & Innovation Group, Romain Ledeuil as Product Manager, Brice Marmonnier as Project Manager, Anne-France Kleis as PMO, Clair Koralewski as Deputy CEO, Anne-Lise Blanc as Legal Counsel, and Kevin Song as Developer Analyst."],
 "tasks": ["Interview and Scope", "Research and ideation", "Design execution and validation"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Interview"],
 "phases": ["Scope Definition", "Business Research", "User Interviews", "User flow", "Wireframing", "User Interface Design"],
 "planning_text": "The project unfolded in 5 main phases: scope definition, business research & user interviews, journeys & userflow, wireframing, interface finalization & prototype.", "planning_img": ("hello-promo-planning.png", "Hello Promo project planning"),
 "research": [
   ("Interviews", ["The research phase was carried out by the Médiaperformances teams. For confidentiality reasons the interviews cannot be shared, but here are the main insights that emerged from this phase."], None),
 ],
 "insights": [
   ("Facebook ads too intrusive", "Make the promise simple and non-intrusive for users. Clarity about how data is used."),
   ("Unsubscribe easily", "One of the main expectations was to be able to unsubscribe at any time."),
 ],
 "solution": [
   ("User flow", ["During the interviews, our research highlighted the critical importance of making the process and the understanding of the service as transparent as possible for users. Our challenge was to determine the optimal number of steps while staying attentive to users' expectations. To meet this need, I decided to simplify the content and offer a simple, intuitive navigation at every step, using clear and explicit calls to action to make the experience enjoyable all the way to the promise: obtaining the voucher in QR Code format. A notable observation was made while simplifying social-network login: we could also simplify the sign-up phase, which allowed us to convert users faster and more efficiently."], ("hello-promo-userflow.png", "Shopper journey user flow")),
   ("Wireframe", ["The wireframes were designed to define the structure and information architecture. During this essential step, I chose to highlight the layout of key elements such as buttons, navigation and content areas in order to present and test it with our users. This collaborative phase allowed us to discuss and incorporate feedback to create a first version of the interface. We then validated the foundations and moved on to the next step, interactive prototyping, to bring the whole interface to life."], ("hello-promo-wireframe.png", "Hello Promo wireframes")),
   ("User interface", [], ("hello-promo-ui.png", "Hello Promo final interfaces")),
   ("Prototype", ["Find the prototype on Figma. For confidentiality reasons the project as a whole is not accessible."], None),
 ],
 "impacts_text": "Since the launch of the Hello Promo web app, we have noted on the one hand a significant improvement in sign-ups thanks to Single Sign-On (SSO) via Facebook Connect, Google Connect and Apple Connect. On the other hand, we have also observed a clear improvement in user retention, with more logins, increased notification opt-ins and more frequent coupon usage.",
 "impacts": [("+23%", "More sign-ups via single sign-on"), ("+30%", "Conversion from Facebook"), ("+11%", "QR Code coupon usage"), ("+56%", "Mobile vs web user conversion")],
 "thanks": [("Thanks to the whole Médiaperformances team", ["Janis Hayat", "Romain Ledeuil", "Brice Marmonnier", "Anne-France Kleis", "Clair Koralewski", "Anne-Lise Blanc", "Kevin Song"])],
},
]
