# -*- coding: utf-8 -*-
# Contenu FR — extrait du fichier Figma "Portfolio Maxime COUDE"

LANDING_FR = {
    "lang": "fr", "other_lang_label": "🇬🇧 EN",
    "title": "Maxime COUDE — Senior Experience Designer Freelance",
    "nav": {"name": "Maxime COUDE", "projects": "Projets", "about": "À propos", "contact": "Me contacter"},
    "hero_h1": "Salut à tous ! Je suis Maxime<br>Senior Experience Designer<br>Freelance",
    "hero_sub": "12 ans dans le design<br>Basé en Bretagne",
    "about_title": "Pour me connaître",
    "about_text": "Designer passionné, j’aime me consacrer et j’accompagne les porteurs de projets innovants. Fort de multiples expériences en ESN comme consultant UX/UI ou en Startup comme Senior Product Designer. Je mets tout en oeuvre pour vous apporter des solutions rapides et concrètes, à la fois simples, ergonomiques et fonctionnelles tout en répondant aux contraintes business et marketing que vous rencontrez.",
    "stats": [("💼", "12 ans"), ("📱", "Mobile"), ("🖥️", "Saas")],
    "offers_title": "Ce que je peux vous apporter ?",
    "offers": [
        ("Designer votre nouveau produit MVP", "Concevoir et designer vos produits pour en faire les leaders du marché"),
        ("Améliorer votre produit existant", "Mettre en valeur votre produit, prioriser et le transformer afin d’être incontournable"),
        ("Délivrer vos équipes de développement", "Délivrez vos équipes rapidement et améliorez votre vélocité de développement"),
        ("Définir votre stratégie Design", "Préparez vos équipes, créez des processus et garantissez l’avenir de votre organisation"),
        ("Former vos équipes au Design d’expérience", "Des processus et méthodologies pour guider vos équipes"),
        ("Mener des Ateliers de conception", "Apprenez à connaître vos utilisateurs, leurs besoins et faites-les participer"),
    ],
    "see_project": "Voir le projet",
    "feedback_title": "Feedbacks",
    "feedback_text": "Tout au long de ma carrière, j’ai eu la chance de collaborer avec des équipes formidables. Voici quelques chiffres et retours qui résument ces années d’expérience.",
    "feedback_author_role": "Co-fondateur @ Sincro",
    "big_stats": [("+20", "Projets accompagnés"), ("+250", "Interviews & ateliers utilisateurs"), ("10 M", "Utilisateurs touchés par mes designs")],
    "clients_title": "Autres clients",
    "clients": ["Audencia", "SNCF", "Afnor", "Université de Nantes", "Zodiac", "Beteam"],
    "contact_h2": "Vous souhaitez me contacter&nbsp;?<br>Envoyez-moi un message",
    "contact_coords": "<strong>Maxime COUDE</strong><br>Product Designer UX/UI Freelance<br>[T] +33(0)6 75 43 44 88<br>[E] maxime.coude@gmail.com",
}

# ——— Libellés communs des pages projets ———
CASE_LABELS_FR = {
    "mission": "La mission", "role": "Mon rôle", "tasks": "Tâches principales",
    "tasks2": "Tâches secondaires", "toolkit": "Design & Research Tool kit",
    "planning": "Planning", "research": "Deck de recherche", "solution": "La solution",
    "impacts": "Les impacts", "thanks": "Remerciements",
    "dpis": ["Découvrir", "Problème", "Idéation", "Solution"],
    "back": "← Retour aux projets", "next": "Projet suivant →",
    "proto_note": "Retrouvez le prototype sur Figma. Pour des raisons de confidentialité le prototype n’est pas accessible pour le moment.",
}

PROJECTS_FR = [
# ============================================================ MMA
{
 "slug": "mma", "name": "MMA", "brand": "MMA", "brand_logo": "logo-mma.png",
 "accent": "#1D7AD9", "hero_bg": "#FFFFFF", "hero_fg": "#2B097C", "hero_title_color": "#2B097C", "hero_align": "left",
 "card_desc_only": False,
 "hero_title": "Faciliter l'assurance pour faciliter la vie",
 "hero_desc": "Remboursements, litiges, relations avec les agents. Découvrez l’ensemble du process design pour rendre encore plus simple la vie des assurés MMA.",
 "hero_img": ("mma-hero.png", "Mockups de l’application mobile MMA"),
 "mission": ["En tant que Senior Product Designer, j’ai dirigé la création de la toute première application mobile MMA, un acteur majeur de l'assurance en France, j'ai été confronté à un défi passionnant et complexe. Notre objectif était de créer un produit avec une expérience utilisateur exceptionnelle en partant de zéro, le tout en collaborant étroitement avec les équipes produits, marketing et de développement internes. L'une des principales priorités était de concevoir une application qui répondrait aux besoins diversifiés des utilisateurs et clients de MMA dans un large éventail de domaines, notamment la santé, l'habitation, l'automobile, la protection juridique, la chasse, l'assurance scolaire, les accidents de la vie et la multirisque. Pour ce faire, nous avons dû relever plusieurs défis clés :"],
 "challenges": [
   ("Compréhension des besoins & recherche", "Rechercher et créer des fonctionnalités adaptées aux besoins spécifiques des utilisateurs dans chaque domaine d'assurance."),
   ("Navigation intuitive et transverse", "Naviguer simplement avec une gamme aussi large de services d'assurance. Organiser les informations de manière logique et aussi simples que possible."),
   ("Personnalisation de l’expérience", "Intégrer des fonctionnalités de personnalisation et de configuration de l’expérience en fonction des préférences. Ex : authentification, notifications etc."),
   ("Sécurité et confidentialité", "Priorité absolue de mettre en place des mesures de sécurité robustes pour garantir que les informations sensibles des utilisateurs étaient protégées de manière optimale."),
   ("Accessibilité", "Créer une interface accessible aux personnes handicapées et/ou déficientes et facile à utiliser pour tous, quel que soit leur niveau de compétence technologique."),
   ("Testing", "Mener des tests utilisateurs fréquents tout au long du processus de développement pour recueillir des commentaires précieux et apporter des ajustements en conséquence."),
 ],
 "role": ["J’ai leadé le product design de l’application Mobile. Durant ce projet j’ai eu l’opportunité de travailler avec les équipes internes composées de Christophe Houze Responsable Organisation Digital UX, Virginie Mahé Chef de projet digital, Rémi Joyaux Product Manager, Maxime Gourloo Proximity Product Owner, Lucie Chevrier UX Designer, Dorian Macerot Assistant Organisation. J’ai mené cette mission en collaboration avec Chris Le Guen Chef de projet de l’agence Team Inside et le soutien de Riham Dir Akilian Product designer chez Monsieur Guiz."],
 "tasks": ["Interview et Scope", "Recherche et idéation", "Exécution du design et validation", "Création, intégration et passation du Design system"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Interview", "Card sorting", "Survey", "ZeroHeight"],
 "phases": ["Scope MVP", "Business Research", "User Interviews", "User flow", "Wireframing", "User Interface Design", "Prototypage & Tests"],
 "planning_text": "Le projet s’est déroulé en 5 grandes phases : définition du scope d’intervention MVP, business research & interviews utilisateurs, userflow & wireframing, conception des interfaces finales et du Design system, prototypage et tests utilisateurs.", "planning_img": ("mma-planning.png", "Planning du projet MMA"),
 "research": [
   ("Concurrence", ["En collaboration avec l’équipe MMA, nous avons comparé de grands concurrents parmi quelques autres applications du secteur de l'assurance qui possèdent une application et un produit similaires. Nous avons examiné comment ils présentent les informations et organisent leur page d'accueil.",
                    "Parmi eux, on retrouve des enseignes comme la GMF, Groupama, Pacifica, mais aussi des acteurs spécialisés (Pure Player) tels qu'Alan et Luko."], ("mma-concurrence.png", "Benchmark concurrentiel")),
   ("Interviews", ["Afin de mieux comprendre les attentes de nos utilisateurs nous avons mené des focus group et des interviews individuels. Cela a été une étape fondamentale dans notre processus de conception de l'application mobile d'assurance. Ils nous ont permis de découvrir ce qui importe vraiment à nos utilisateurs, de résoudre les problèmes potentiels avant le lancement et de créer une expérience utilisateur exceptionnelle. Pour des raisons de confidentialité les interviews ne peuvent être partagées, mais voici les principaux insights qui ont émergé durant cette phase."], None),
 ],
 "insights": [
   ("Dashboard personnalisé", "Proposer un dashboard personnalisé et évolutif : derniers remboursements, suivre un sinistre, accéder à l’assistance, push des actualités selon la saisonnalité."),
   ("Quick actions", "Accès rapide aux différentes actions récurrentes selon les typologies de contrat : demander un remboursement, déclarer un sinistre, contacter mon agent, éditer une attestation."),
 ],
 "solution": [
   ("User flow", ["Après une réflexion approfondie et la réalisation de plusieurs ateliers de card sorting, nous avons entamé le processus de cartographie des parcours utilisateurs. Notre objectif était de perfectionner la navigation et de structurer l'architecture de l'information de manière à maintenir un pattern cohérent, assurant ainsi une compréhension aisée pour l'ensemble de nos utilisateurs."], ("mma-userflow.png", "User flow de l’application MMA")),
   ("Wireframe", ["Au cours de la phase de wireframing, nous avons matérialisé les concepts de navigation et d'architecture de l'information, qui ont constitué une base solide pour la conception des interfaces finales. En parallèle, nous avons également travaillé sur différentes features en réponse aux attentes et problématiques de nos utilisateurs. C’est en intégrant tous ces éléments que nous avons minutieusement conçu les patterns et la disposition des interactions clés, tels que les boutons, les menus de navigation et les zones de contenu.",
                  "L'approche collaborative a joué un rôle central dans la réussite de cette phase. Elle nous a offert l'opportunité de recueillir des idées précieuses et des retours de l’ensemble des parties prenantes, ce qui a grandement enrichi notre compréhension des besoins des utilisateurs."], ("mma-wireframe.png", "Wireframes de l’application MMA")),
   ("User interface", ["Après la validation de nos concepts, j'ai travaillé sur l'UI finale des interfaces. La création d'un design system était essentielle à la réussite d'un tel projet. Cela nous a permis de concevoir une interface utilisateur soigneusement pensée et parfaitement adaptée à tous les devices."], ("mma-ui.png", "Interfaces finales de l’application MMA")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "L’application étant en cours de développement je ne suis pas en mesure de donner plus d’informations sur l’impact de notre travail. Les données seront actualisées prochainement.",
 "impacts": [("4,7", "Note sur les stores"), ("x %", "Téléchargements"), ("+100k", "Utilisateurs actifs"), ("81 %", "Satisfaction utilisateur"), ("85-15", "Consultation Mobile vs Web")],
 "thanks": [
   ("Merci à toute l’équipe MMA", ["Christophe Houze", "Virginie Mahé", "Rémi Joyaux", "Maxime Gourloo", "Lucie Chevrier", "Dorian Macerot"]),
   ("Merci également aux externes", ["Chris Le Guen", "Riham Dir Akilian"]),
 ],
},
# ============================================================ SINCRO SAAS
{
 "slug": "sincro-saas", "name": "Sincro Saas", "brand": "Sincro", "brand_logo": "logo-sincro-white.png",
 "accent": "#4975E9", "hero_bg": "linear-gradient(135deg, #4975E9 0%, #7B61FF 100%)", "hero_fg": "#FFFFFF", "hero_split": True,
 "card_bg": True, "card_text": "left",
 "hero_bg_img": "decor-sincro-gradient.png",
 "hero_title": "La suite applicative pour une gestion plus facile que jamais",
 "hero_desc": "Achats, facture, fournisseurs, devoir de vigilance, saisie des temps… Découvrez le processus design qui a simplifié la manière de gérer l’écosystème de la prestation intellectuelle.",
 "hero_img": ("sincro-saas-hero.png", "Interface de la suite Sincro sur desktop"),
 "mission": ["Sincro connecte les acteurs de la prestation intellectuelle au sein de sa plateforme Saas de gestion et d’intermédiation, leur offrant les outils et les services pour collaborer ensemble dans un cadre sécurisé et interconnecté.",
             "Dans un marché ultra concurrentiel des ERP, Sincro s’est fixé l’objectif d’être la plateforme Saas all-in-one permettant à tous ses utilisateurs de booster et simplifier leur activité au quotidien. Dans ce contexte le challenge principal a été de redesigner et concevoir une suite de produits au service des différents métiers."],
 "challenges": [
   ("Unifier les solutions par une expérience unique", ""),
   ("Créer l’image & le Branding", ""),
   ("Construire un design system scalable", ""),
   ("Repenser et créer les features métier", ""),
 ],
 "role": ["En tant que tout premier employé comme Designer UX/UI chez Sincro, j'ai eu le privilège de mener à bien diverses missions majeures pour le développement de la start-up. Mon parcours a débuté par la recherche utilisateur, s'est poursuivi avec la conception du produit, et a impliqué une évolution significative de l'expérience utilisateur en introduisant des fonctionnalités clés, pour finalement déboucher sur une refonte totale de l'interface utilisateur (UI). Au cours de cette enrichissante expérience, j'ai également eu l'occasion de jouer un rôle essentiel dans la création de l'identité visuelle de la marque Sincro, dont nous sommes aujourd'hui extrêmement fiers. Par ailleurs, j'ai étroitement collaboré avec les équipes techniques, marketing et commerciales, sensibilisant ces dernières aux enjeux de l'expérience utilisateur tout en apportant mon soutien grâce à mes compétences en design. En conclusion, cette expérience m'a offert l'opportunité de travailler au sein d'une équipe exceptionnelle, notamment en compagnie du cofondateur aux multiples casquettes, assumant les rôles de CTO, Product Manager et Commercial, Damien Mordaque, ainsi qu'avec le fondateur Lionel Frizon, et toutes les équipes de développement et métier, composées d'une vingtaine de personnes."],
 "tasks": ["Design stratégique : Business x Produit", "UX Researcher : Interview, Persona, Expérience Map, Card sorting…", "Brand Designer : Branding", "UX Designer : Userflow, Wireframing, A/B testing", "UI Designer : Conception des interfaces finales, Design System"],
 "tasks2": ["Motion Designer : Animations", "Graphic Designer : Communication et slides deck", "Design évangéliste : Animation d’ateliers & partage de connaissances"],
 "toolkit": ["Miro", "Board", "Interview", "Survey", "Card sorting", "Maze", "Sketch", "Zeplin", "Figma", "After Effects"],
 "phases": ["Stakeholders Interview", "Scope Définition", "Business Research", "User Interviews", "Wireframing", "User Interface Design", "Usability Testing", "Design Update"],
 "planning_text": "Nous avons le plus souvent travaillé dans un format agile en sprints de 3 semaines. Ci-dessous un exemple du déroulement de l’un de nos sprints Design.", "planning_img": ("sincro-saas-planning.png", "Planning d’un sprint Design Sincro"),

 "research": [
   ("Experience Map", ["Pour chaque refonte partielle du produit et chaque nouvelle fonctionnalité, nous avons organisé plusieurs ateliers dans le but d'approfondir notre compréhension des attentes et des comportements des utilisateurs. Que ce soit en créant des expérience maps, en menant des entretiens individuels, en organisant des sessions de tri de cartes ou en utilisant la méthode du \"6 to 1\", ces approches et méthodologies nous ont permis d'acquérir une meilleure compréhension de nos utilisateurs ainsi que leurs attentes dans leur domaine métier.",
                       "Voici un exemple d'atelier de création d'une expérience map que nous avons réalisé en collaboration avec un panel de 10 utilisateurs lors d’un atelier réalisé en amont de la refonte du produit Sourcing."], ("sincro-saas-expmap.png", "Atelier Experience Map")),
   ("Site Map", ["D’autre part, j’ai aussi matérialisé le site map de l’ensemble de la solution pour le partager avec toute l’équipe produit. Cela nous a permis, pour chaque nouvelle fonctionnalité, de définir une représentation hiérarchique des pages et des fonctionnalités afin d'optimiser l'expérience utilisateur. Cet exercice garantit une organisation logique, une meilleure accessibilité et une compréhension rapide de la structure qui de fait contribue à accroître in fine la satisfaction et l’expérience des utilisateurs et à favoriser leur rétention sur la plateforme."], ("sincro-saas-sitemap.png", "Site map de la suite Sincro")),
 ],
 "insights": [],
 "solution": [
   ("Dashboard", ["Le tableau de bord personnalisable fournit à tous les utilisateurs une vue globale de leur activité grâce à l'intégration de widgets interactifs. Les widgets permettent de remonter en prime les informations essentielles dont l’utilisateur doit disposer pour réaliser son métier au quotidien. Couplé à un centre de notifications et à un moteur de recherche, cela guide et facilite la prise d’action de l’utilisateur et rend l'expérience encore plus fluide."], ("sincro-saas-dashboard.png", "Dashboard Sincro")),
   ("Liste des contrats", ["Dans le module de gestion, vous trouverez une liste de contrats de vente. Cette liste est hautement personnalisable, ce qui permet aux utilisateurs d'avoir une vue d'ensemble, de manipuler et de réaliser des actions individuelles ou groupées en fonction du besoin."], ("sincro-saas-synthese-absences.png", "Liste des contrats — synthèse contrat, absences")),
   ("Marketplace", ["Booster l’activité c’est permettre de favoriser la croissance de l'activité grâce à la capacité qu’offre la solution aux clients afin de mettre en relation des talents avec l'ensemble de son réseau. La Marketplace Sincro est un espace de centralisation des besoins auxquels chaque entreprise membre a l'opportunité de répondre en proposant des ressources ultra qualifiées."], ("sincro-saas-marketplace.png", "Marketplace Sincro")),
   ("Design system", ["J'ai dirigé de manière transversale la conception et la mise à jour continue du Design System Sincro. Cette source de documentation a permis à l’ensemble de nos équipes produits et techniques d’améliorer considérablement la vélocité de notre delivery."], ("sincro-saas-designsystem.png", "Composants du Design System Sincro")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "",
 "impacts": [],
 "thanks": [("Merci à l’équipe Sincro", ["Damien Mordaque", "Kevin Mouzet", "Emile Leenhardt"])],
},
# ============================================================ SINCRO MOBILE
{
 "slug": "sincro-mobile", "name": "Sincro Mobile", "brand": "Sincro", "brand_logo": "logo-sincro.png",
 "accent": "#1FA26A", "hero_bg": "#FFFFFF", "hero_fg": "#000000", "hero_title_color": "#6482D4", "hero_align": "right",
 "card_bg": True, "card_text": "right", "card_fg": "#FFFFFF", "card_title_color": "#FFFFFF",
 "card_bg_color": "linear-gradient(135deg, #4975E9 0%, #7B61FF 100%)", "card_brand_logo": "logo-sincro-white.png", "card_brand_logo_alt": "logo-sincro.png",
 "hero_title": "L’app de poche des consultants en mission",
 "hero_desc": "Saisie des temps, rapport d’activité, absences. La meilleure app quotidienne pour tous les consultants.",
 "hero_img": ("sincro-mobile-hero.png", "Écrans de l’application mobile Sincro"),
 "mission": ["Sincro est l'application mobile attendue par tous les consultants en mission. Le service permet aux utilisateurs de saisir facilement et rapidement leur temps d'activité, où qu'ils se trouvent. Grâce à sa connexion directe avec la solution web, les utilisateurs peuvent remplir et compléter leur rapport mensuel d'activité en toute mobilité. De plus, il était essentiel de simplifier la démarche de demande d'ajout de contrat, la rendant plus accessible que jamais, directement auprès de leur manager. Pour les managers, Sincro est un outil puissant qui leur permet non seulement d'ajouter de nouveaux contrats, mais aussi de valider les rapports, d'avoir une vue d'ensemble complète, incluant le temps de production, le temps passé en intercontrat et les absences de toute leur équipe. Cette solution offre également la capacité de mesurer le TACE (Taux d'activité Congés exclus). Notre objectif principal était de simplifier au maximum l'expérience des utilisateurs et d'améliorer la communication entre ces deux groupes d'utilisateurs. Sincro a été conçue pour être aussi intuitive et efficace que possible, rendant la gestion du temps et des contrats aussi simple que possible pour tous les utilisateurs."],
 "challenges": [
   ("Simplifier l’expérience de saisie des temps", ""),
   ("Substituer les demandes mail aux managers", ""),
   ("Offrir un canal d’échange dédié", ""),
   ("Automatiser & notifier les rappels de saisie", ""),
 ],
 "role": ["En tant que Product Designer, j'ai dirigé l'ensemble des travaux liés à la conception de l'application. Au cours de ce projet, j'ai eu le plaisir de collaborer étroitement avec notre Product Manager interne, Damien Mordaque, ainsi qu'avec les équipes de l'agence Creatiwity pour le développement de l'application, composées de Johan Dufau en tant que Lead Dev Mobile Backend et Julien Blatecky en tant que Lead Dev Mobile Frontend."],
 "tasks": ["Interview et Scope", "Recherche et idéation", "Exécution du design et prototypage", "Validation des designs"],
 "tasks2": [],
 "toolkit": ["Miro", "Sketch", "Zeplin", "Interview", "After Effects", "Maze"],
 "phases": ["Scope Définition", "User Interviews", "User flow", "Wireframing", "User Interface Design", "Prototypage", "Tests utilisateurs"],
 "planning_text": "Le projet s’est déroulé en 4 grandes phases : définition du scope d’intervention, interviews utilisateurs, parcours & userflow, wireframing, finalisation des interfaces, prototypage et tests utilisateurs.", "planning_img": ("sincro-mobile-planning.png", "Planning du projet Sincro Mobile"),
 "research": [
   ("Analyse des usages", ["Premièrement pour constituer notre deck de recherche, nous avons exploité les données (KPI) de la solution web afin d'analyser les usages des utilisateurs de la plateforme. Notre analyse s'est portée sur différents critères en fonction des typologies d'utilisateurs : population/audience, mobilité/itinérants, temporalité des besoins, fréquence, engagement, performance et satisfaction. Nous avons également croisé l'ensemble de ces données avec des entretiens individuels.",
                          "Pour des raisons de confidentialité les données du visuel ci-dessus sont masquées."], ("sincro-mobile-kpi.png", "Analyse des KPI de la solution web")),
   ("Concurrence", ["Dans notre deck de recherche, nous avons également analysé l'ensemble des acteurs du marché concurrentiel. Cela nous a permis d'identifier les bonnes pratiques, mais aussi d'auditer les solutions afin de proposer une expérience encore plus intuitive lors de la conception de l'application Sincro."], ("sincro-mobile-concurrence.png", "Analyse concurrentielle")),
 ],
 "insights": [],
 "solution": [
   ("User interface", ["Une fois le travail d'idéation exploré, nous avons travaillé sur la conception des UI finales. En voici une synthèse."], ("sincro-mobile-ui.png", "Synthèse des interfaces finales")),
   ("Documentation", ["Afin de maximiser l'adhésion de nos utilisateurs, nous avons également documenté l'ensemble des fonctionnalités disponibles dans l'application. Ce travail a permis à nos clients de promouvoir en interne le lancement de l'application et d'accroître l'engagement de leurs collaborateurs."], ("sincro-mobile-doc.png", "Documentation des fonctionnalités")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "Après le déploiement sur les stores en mars 2019, nous avons analysé les résultats d’utilisation de l’application versus l’usage web sur les 3 mois suivants. Voici quelques données majeures :",
 "impacts": [("+1500", "Rapports d’activité saisis par les consultants"), ("+350", "Ajouts de contrat par les managers"), ("45%", "Utilisateurs ayant utilisé la messagerie in-app"), ("-36%", "Retards de saisie des rapports mensuels d’activité")],
 "thanks": [
   ("Merci à l’équipe Sincro", ["Damien Mordaque", "Kevin Mouzet", "Emile Leenhardt"]),
   ("Merci également à l’agence Creatiwity", ["Johan Dufau", "Julien Blatecky"]),
 ],
},
# ============================================================ AFNOR
{
 "slug": "afnor", "name": "Afnor", "brand": "Afnor — Opéra 2", "brand_logo": "logo-afnor.png",
 "accent": "#8C6A45", "hero_bg": "#F3E7DC", "hero_fg": "#2B097C", "hero_title_color": "#2B097C", "hero_align": "left", "card_cta_color": "#2B097C",
 "hero_title": "Une plateforme unique, des audits transparents",
 "hero_desc": "Avec plus de 3500 audits, Opéra 2 permet aux clients de suivre chacune des étapes des audits tout en simplifiant les échanges au sein de la plateforme avec les auditeurs.",
 "hero_img": ("afnor-hero.png", "Interface de la plateforme Opéra 2"),
 "mission": ["Lancé par Afnor en 2016, OPERA est une plateforme SaaS de suivi d'audit. Destinée aux clients souhaitant être audités, elle facilite le processus, de la préparation à la prise de décision, tout en permettant aux clients de collaborer avec leur auditeur et leur chargé de clientèle sur une plateforme commune. Initialement plus orienté sur une refonte graphique et donc UI Design, j’ai accompagné mes clients sur une refonte plus profonde de l’UX de la plateforme."],
 "challenges": [
   ("Audit UX & refonte ergonomique complète", ""),
   ("Simplifier les processus de suivi et la saisie", ""),
   ("Création d’un design system", ""),
   ("Renouer avec les utilisateurs", ""),
 ],
 "role": ["En tant que Product Designer, j'ai accompagné Afnor dans la refonte ergonomique globale de la solution, en intégrant une phase d'amélioration de l'expérience utilisateur jusqu'à la conception d'un design system complet. Pour ce projet j’ai eu l’opportunité de travailler avec l’équipe interne Afnor responsable du projet Opéra composée de Marie Sperandio Responsable de la transformation numérique, Ilija Spaargaren Chef de projet, Frédéric Dorinet Product Owner, Williams Bouton CSM. Pour le développement, l’agence Anakeen a été représentée par Moez Marrakchi Ingénieur en développement, Lydie Derrien Directrice projets et Santiago Mauro Développeur Fullstack."],
 "tasks": ["Interview et Scope", "Recherche et idéation", "Exécution du design et validation", "Création, intégration et passation du Design system"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Eye Tracking"],
 "phases": ["Audit", "Shadowing & Eye Tracking", "Architecture de l’information", "Wireframing", "User Interface Design & Prototypage"],
 "planning_text": "Le projet s’est déroulé en 4 grandes phases : audit, shadowing & eye tracking, architecture de l’information & wireframing, finalisation des interfaces & prototype.", "planning_img": ("afnor-planning.png", "Planning du projet Afnor"),
 "research": [
   ("Shadowing", ["Le shadowing est une des méthodes d’observation que j’ai mises en place au début de la phase de recherche. Cette méthode m’a permis d’observer le comportement et les interactions d’un panel d’utilisateurs avec le produit existant.",
                  "Lors de l’atelier nous avons sollicité individuellement 10 utilisateurs et leur avons demandé d’effectuer des tâches habituelles sur la plateforme Opéra 2. On s’est positionné derrière eux, en évitant de trop perturber leur environnement afin de les observer manipuler le service. Durée 40-50 minutes. Enfin nous avons finalisé l’atelier par une grille d’évaluation ergonomique."], ("afnor-shadowing.png", "Atelier de shadowing")),
   ("Eye Tracking", ["L’oculométrie (eye tracking) est une technologie qui mesure les mouvements oculaires. Cette technique nous permet de comprendre en détail le parcours oculaire des utilisateurs face à une interface afin de mieux comprendre ce qui retient le plus leur intérêt. L’eye tracking est actuellement considéré comme étant une méthode de recherche UX très précise. Dispositif : utilisation de la solution Tobii Pro Nano.",
                     "Lors de l’atelier nous avons sollicité individuellement 8 utilisateurs et leur avons demandé d’effectuer des tâches habituelles sur la plateforme Opéra 2. La caméra a permis de suivre, d’enregistrer et d’analyser les mouvements des yeux des utilisateurs lors de leur manipulation sur le service."], ("afnor-eyetracking.png", "Atelier d’eye tracking — évaluation")),
 ],
 "insights": [],
 "solution": [
   ("La refonte", ["La refonte ergonomique a engendré une harmonisation et une uniformisation des comportements suivants : la création de systèmes et de patterns en fonction de la typologie de la page, qu'il s'agisse de formulaires, de tableaux, de tableaux de bord, etc. L'amélioration de l'assistance à la saisie. La simplification des tâches à accomplir grâce à des to do goals (notifications). Une révision de la navigation pour la rendre plus lisible, claire et fluide, en combinant la sidebar et la barre d'onglets. Une amélioration de la lisibilité générale, accompagnée d'info-bulles lorsque nécessaire. Une réduction de la complexité des interfaces pour alléger la charge mentale des utilisateurs. Une amélioration des performances globales, notamment en réduisant les temps de réponse. Un wording plus clair et plus compréhensible pour l'utilisateur."], None),
   ("User interface — Dashboard", ["Le nouveau tableau de bord permet aux utilisateurs de visualiser en un coup d’œil les rapports en attente d’une action, les rapports en attente d’une action auditeur et les rapports archivés."], ("afnor-dashboard.png", "Dashboard Opéra 2")),
   ("Liste des audits & avancement", ["La navigation combinant sidebar et barre d’onglets permet de suivre chaque étape de l’audit : revue préparatoire et plan d’audit, constats, rapport, commentaires, rapport définitif et zone d’échange."], ("afnor-audits.png", "Liste des audits et suivi d’avancement")),
   ("Détail d’un constat", ["Chaque constat (NC mineure, hors champ, etc.) dispose d’une fiche détaillée regroupant les sites repris, les réponses et propositions d’actions."], ("afnor-constat.png", "Détail d’un constat")),
   ("Rapport définitif", ["Le workflow de validation permet de demander des corrections ou de valider le rapport d’audit, de soumettre au RA et d’envoyer le rapport définitif."], ("afnor-rapport.png", "Workflow du rapport définitif")),
   ("Prototype", ["__PROTO__"], None),
 ],
 "impacts_text": "La refonte ergonomique a permis :",
 "impacts": [("+64 %", "Satisfaction utilisateurs"), ("÷3", "Temps nécessaire pour achever un audit"), ("+49%", "Saisie des audits in-app"), ("÷2", "Temps de saisie"), ("x3", "Gain de temps pour le développement")],
 "thanks": [
   ("Merci à toute l’équipe Afnor", ["Marie Sperandio", "Ilija Spaargaren", "Frédéric Dorinet", "Williams Bouton"]),
   ("Merci également aux équipes Anakeen", ["Moez Marrakchi", "Santiago Mauro", "Lydie Derrien"]),
 ],
},
# ============================================================ RATP
{
 "slug": "ratp", "name": "RATP", "brand": "RATP — Visiter Paris", "brand_logo": "logo-ratp.png",
 "accent": "#00936E", "hero_bg": "#FFFFFF", "hero_fg": "#2B097C", "hero_title_color": "#00C4B4", "card_cta_color": "#00C4B4",
 "card_bg": True, "card_text": "center",
 "hero_title": "Restez informé pour voyager plus sereinement",
 "hero_desc": "Plus de 10 millions de personnes en France utilisent les transports de la RATP (bus, métro, RER, tramway) chaque jour.",
 "hero_img": ("ratp-hero.png", "Application Visiter Paris — composants d’alerte"),
 "mission": ["En tant que designer d'expérience utilisateur, j'ai contribué à la création de l'application \"Visiter Paris\", dédiée aux voyageurs qui souhaitent explorer Paris et ses environs. Compte tenu des quelque 10 millions de voyageurs qui empruntent quotidiennement le réseau urbain RATP, il est essentiel de prendre en compte les perturbations parfois importantes dans les transports, sources de préoccupations pour les voyageurs. Notre objectif principal était de concevoir une expérience utilisateur apaisante à travers l'application, afin d'instaurer un sentiment de sérénité lors de leurs déplacements. Pour ce faire, nous avons mis en place des solutions pour anticiper les perturbations, fournir des informations en temps réel et rendre le voyage aussi agréable et fluide que possible."],
 "challenges": [
   ("Informer les voyageurs", ""),
   ("Améliorer la sérénité", ""),
 ],
 "role": ["J'ai été sollicité par la RATP pour concevoir des composants graphiques d'alerte, tout en respectant les directives préétablies et la charte graphique en place. Mon objectif était d'assurer une intégration harmonieuse de ces composants dans le contexte défini, en optimisant l'expérience utilisateur pour les utilisateurs finaux."],
 "tasks": ["Exécution du design et validation"],
 "tasks2": [],
 "toolkit": ["Photoshop", "Illustrator"],
 "phases": ["Création des composants", "Accompagnement dans l’intégration"],
 "planning_text": "Création des composants, puis coordination de l’intégration.", "planning_img": ("ratp-planning.png", "Planning du projet RATP"),
 "research": [],
 "insights": [],
 "solution": [
   ("User interface — Mes messages", ["Exemples de messages d’alerte conçus pour l’application : « Du 25 juillet au 23 août inclus, le trafic est interrompu sur le RER A entre La Défense et Auber. Attention : si vous souhaitez visiter l’Arc de Triomphe (station Charles de Gaulle - Étoile), merci d’emprunter les lignes de métro 1, 2 ou 6. » — « Du 15 juillet au 22 août inclus, le trafic est interrompu sur le RER C entre Javel, Avenue Henri Martin et Gare d’Austerlitz. Attention : si vous souhaitez visiter la tour Eiffel, l’Hôtel des Invalides, le Musée de l’Armée ou la cathédrale Notre-Dame, merci d’emprunter les lignes de métro correspondantes. »"], ("ratp-messages.png", "Écrans « Mes messages » de l’application Visiter Paris")),
 ],
 "impacts_text": "Depuis l’intégration des messages d’alertes il a été observé une amélioration de la satisfaction client de 17 % et 57 % d’entre eux ont précisé qu’ils voyagent plus sereinement avec des informations et alertes en temps réel lors de leurs déplacements.",
 "impacts": [("+17 %", "Satisfaction utilisateurs"), ("+57 %", "Plus sereins lors des déplacements")],
 "thanks": [("Remerciements", ["Farid Sayah"])],
},
# ============================================================ HELLO PROMO
{
 "slug": "hello-promo", "name": "Hello Promo", "brand": "Hello Promo — Médiaperformances", "brand_logo": "logo-hello-promo.png",
 "accent": "#3FBF61", "hero_bg": "linear-gradient(23deg, #6AE5B3 12%, #66E2B0 30%, #5CD9A8 46%, #54D3A2 54%)", "hero_fg": "#4C4C4C", "hero_align": "left",
 "card_bg": True, "card_text": "left",
 "hero_title": "Obtenez votre QR Code et commencez à faire des économies en caisse",
 "hero_title_html": "<span style=\"color:#FFFFFF\">Obtenez votre QR Code</span> <span style=\"color:#0A0A0A\">et commencez à faire des économies en caisse</span>",
 "hero_desc": "L’application pour profiter de bons de réduction immédiats et dématérialisés en caisse, valables dans vos hypermarchés.",
 "hero_img": ("hello-promo-hero.png", "Web app Hello Promo — parcours QR Code"),
 "mission": ["Hello Promo est une solution marketing (Web App) permettant à la communauté d'utilisateurs de bénéficier de nombreuses réductions gratuites utilisables dans les supermarchés et hypermarchés grâce à la présentation d'un QRCode. Chaque promotion est accessible sur différents canaux de réseaux sociaux tels que Facebook, Instagram ou Twitter. En tant que senior product designer, j'ai accompagné mes clients dans la refonte du parcours du \"shopper\" afin de proposer une expérience plus simple et intuitive, favorisant l'adhésion et la rétention des utilisateurs, tout en respectant les droits liés aux données privées."],
 "challenges": [
   ("Simplifier l’inscription", ""),
   ("Augmenter la rétention", ""),
 ],
 "role": ["J’ai leadé le product design de l’application web. Durant ce projet j’ai eu l’opportunité de travailler avec l’équipe Médiaperformances porteuse du projet, composée de Janis Hayat comme Chef de groupe marketing et innovation, Romain Ledeuil comme Chef de produit, Brice Marmonnier comme Chef de projet, Anne-France Kleis comme PMO, Clair Koralewski comme DGA, Anne-Lise Blanc comme Juriste et Kevin Song comme Développeur analyste."],
 "tasks": ["Interview et Scope", "Recherche et idéation", "Exécution du design et validation"],
 "tasks2": [],
 "toolkit": ["Miro", "Figma", "Interview"],
 "phases": ["Scope Définition", "Business Research", "User Interviews", "User flow", "Wireframing", "User Interface Design"],
 "planning_text": "Le projet s’est déroulé en 5 grandes phases : définition du scope d’intervention, business research & interviews utilisateurs, parcours & userflow, wireframing, finalisation des interfaces & prototype.", "planning_img": ("hello-promo-planning.png", "Planning du projet Hello Promo"),
 "research": [
   ("Interviews", ["La phase de recherche a été réalisée par les équipes de Médiaperformances. Pour des raisons de confidentialité les interviews ne peuvent être partagées, mais voici les principaux insights qui ont émergé durant cette phase."], None),
 ],
 "insights": [
   ("Ads Facebook trop intrusives", "Rendre la promesse simple et non intrusive pour les utilisateurs. Clarté sur l’utilisation des données."),
   ("Se désabonner simplement", "Une des attentes principales a été de pouvoir aussi se désabonner à tout moment."),
 ],
 "solution": [
   ("User flow", ["Au cours des entretiens, notre recherche a mis en avant l'importance capitale de rendre le processus et la compréhension du service aussi transparents que possible pour les utilisateurs. Notre défi était de déterminer le nombre optimal d'étapes à suivre tout en restant attentifs aux attentes des utilisateurs. Pour répondre à ce besoin, j'ai pris la décision de simplifier le contenu et de proposer une navigation simple et intuitive à chaque étape, en utilisant des call to action clairs et explicites pour rendre l'expérience appréciable jusqu'à la promesse, l’obtention du BRI sous le format QRCode. Une observation notable a été faite lors de la simplification de la connexion via les réseaux sociaux, révélant que nous pouvions également simplifier la phase d'adhésion, ce qui nous a permis de convertir les utilisateurs de manière plus rapide et efficace."], ("hello-promo-userflow.png", "User flow du parcours shopper")),
   ("Wireframe", ["Les wireframes ont été conçus dans le but de définir la structure et l'architecture de l'information. Au cours de cette étape essentielle, j'ai choisi de mettre en lumière la disposition des éléments clés tels que les boutons, la navigation et les zones de contenu afin de la présenter et de la tester auprès de nos utilisateurs. Cette phase collaborative nous a permis de discuter et d'incorporer les feedbacks pour créer une première version de l'interface. Par la suite, nous avons validé les fondations et progressé vers l'étape suivante, celle du prototypage interactif, pour donner vie à l'ensemble de l'interface."], ("hello-promo-wireframe.png", "Wireframes Hello Promo")),
   ("User interface", [], ("hello-promo-ui.png", "Interfaces finales Hello Promo")),
   ("Prototype", ["Retrouvez le prototype sur Figma. Pour des raisons de confidentialité l’ensemble du projet n’est pas accessible."], None),
 ],
 "impacts_text": "Depuis le lancement de l'application web Hello Promo, nous avons constaté d’une part une amélioration significative des inscriptions grâce à la mise en place du Single Sign-On (SSO) via Facebook Connect, Google Connect et Apple Connect. D'autre part, nous avons également remarqué une nette amélioration de la rétention des utilisateurs, avec une augmentation du nombre de connexions, une hausse de l’activation des notifications et une utilisation plus fréquente des coupons.",
 "impacts": [("+23%", "Augmentation des inscriptions via single sign-on"), ("+30%", "Conversion depuis Facebook"), ("+11%", "Utilisation des coupons QRCode"), ("+56%", "Conversion des utilisateurs sur mobile vs web")],
 "thanks": [("Merci à toute l’équipe Médiaperformances", ["Janis Hayat", "Romain Ledeuil", "Brice Marmonnier", "Anne-France Kleis", "Clair Koralewski", "Anne-Lise Blanc", "Kevin Song"])],
},
]
